name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildAndTestJava8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew  
    - name: Run unit tests with gradle and Java 8
      run: ./gradlew test
      
  buildAndTestJava14:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew  
    - name: Run unit tests with gradle and Java 14
      run: ./gradlew test
